### ISSUE TITLE
Hidden Text in Folder Pane

### ISSUE THREAD

**Issue by mlmilliman** [spymastermatt/thunderbird-monterail#10]
Awesome work on this skin/theme! I now enjoy using Thunderbird again. It now feels like a modern e-mail client.

I've tested the Monterail and Dark themes and I've noticed that folders with their names in italics display in the background color or with no color. If I select the folder then it turns white so it is visible but when I select another folder it disappears again. The picture below shows the issue. 

![screenshot from 2017-04-27 15-12-11](https://cloud.githubusercontent.com/assets/11722868/25504926/f2eb854e-2b5c-11e7-9c30-3516fb02e880.png)

Maybe these elements have a different class name than treechildren that need to be defined.

**Comment by spymastermatt** [comment]
@mlmilliman Hmm, you've stumped me there. I don';t have any folders in italics and of course (ironically) I can't see the names on your screenshots. What makes them be italic? Are they special folders in some way?

I see you have a full theme applied as well, could you try it with the theme disabled in case its a conflict with the theme (still needs fixing but at least helps me track it down)

**Comment by mlmilliman** [comment]
They are typically system folders. The one under Inphotonics Research is _[Gmail]_. Under Comcast there are _Chats, DUMPSTER, and EMailed Contacts_. The Inphotonics Research is really a Gmail account that I access via IMAP. I don't know what makes these folders different and I don't have a way to look at the elements to see their formatting.

I removed my theme but it didn't make any difference. I left it disabled because I like the cleaner look. I wish I could have been of more help.

**Comment by spymastermatt** [comment]
@mlmilliman ok thanks. I'll set up a Gmail account to see if I can replicate the problem. I'll let you know when/if I manage to fix it

**Comment by spymastermatt** [comment]
@mlmilliman, sorry for being quiet for the past few days, I have been working on a big update (coming tomorrow hopefully) which fixes almost all open issues, after which I will look into this issue

**Comment by mlmilliman** [comment]
No problem. We are all busy. My issue is relatively minor, but I'm delighted that you are going to produce a fix. I actually enjoy using Thunderbird again due to your UI improvements. It now looks like a modern e-mail client. Thanks your your great work.

**Comment by mlmilliman** [comment]
Thanks for the update, but those special Google folders are still not showing. Well, the icon shows but the text is the same color as the background until highlighted. I like the other changes made. The theme looks much cleaner.

**Comment by mlmilliman** [comment]
The latest pull from git fixed this issue. Looks wonderful with all themes. Closed! Thanks for the fix.
