### ISSUE TITLE
Font doesn't support accentuation

### ISSUE THREAD

**Issue by fxbenard** [spymastermatt/thunderbird-monterail#12]
Lovely themes - Great job.
The problem is that your font doesn't render properly accentuation characters.
é, à, ç etc. shows with ? instead

**Comment by spymastermatt** [comment]
@fxbernard glad you like it!
Ah ok. I will need to find a different font then. In the mean time, if you open your userChrome.css and comment the font-family line from the * section (see the font size line for how to comment CSS). This will go back to using your system font

* {
	font-family: LightSans; <<This line
	/*font-size:14px;*/
}

**Comment by fxbenard** [comment]
@spymastermatt +1 It does the trick
My bad it wasn't your themes's font issue.
I checked your embeded font and accentuated characters are supported.
Wrong encoding for some newsletters and it happens just after I installed your theme.

BTW: on windows didn't was able to make variants themes to work properly

**Comment by spymastermatt** [comment]
Ah ok good to hear 🙂.
I'm aware of the windows issues and am working on them.
I'll close this issue but if you want to check the progress on the colour issues check issue #9
