### ISSUE TITLE
fonts don't support utf8 symbols, goes back to fallbacks

### ISSUE THREAD

**Issue by ozo2003** [spymastermatt/thunderbird-monterail#13]
![screenshot_2017-04-28_10-33-18](https://cloud.githubusercontent.com/assets/5328929/25518860/2506b2b4-2bfe-11e7-9a8b-cbf6f9f45f08.png)
![screenshot_2017-04-28_10-33-31](https://cloud.githubusercontent.com/assets/5328929/25518861/2506fb0c-2bfe-11e7-82fa-e632aaf34680.png)

any chance to get fonts that would support utf8 symbols properly?

**Comment by spymastermatt** [comment]
Hey, sorry for being quiet for the past few days, I have been working on a big update (coming tomorrow hopefully) which fixes almost all open issues, after which I will look into selecting a new font.
In the mean time, if you comment out the font-family line under the * section, you will get your system font back :)

**Comment by spymastermatt** [comment]
@ozo2003 Please download that latest version. Whilst I don't think it will fix your font issues, it does allow you to choose a font to use by editing a variable in userChrome.css. I am away for a week now but I will look into the font rendering issue when I get back

**Comment by ozo2003** [comment]
ok, changing font-family works. at least that's good
