### ISSUE TITLE
Multiple Profiles

### ISSUE THREAD

**Issue by Girtablulu** [spymastermatt/thunderbird-monterail#16]
Hello 

Great design you did but sadly I have a little problem, on my Thunderbird I'm using 2 different profiles. The design works for the first profile but not for my second one, do you know a solution or what do I have to do to get it working for this one?

**Comment by spymastermatt** [comment]
Hmm, not sure. I'll look into it for you.

**Comment by spymastermatt** [comment]
@Girtablulu Try opening thunderbird with your second profile and then open preferences (Tools->Options->Advanced). After that, click the 'Config Editor' button, accept the warning and then search for directory. Your directory should be the value of the parameter mail.server.server1.directory. This is the path where you should extract the chrome folder.

**Comment by spymastermatt** [comment]
@Girtablulu also make sure you get the latest version as I have just made a huge update which fixes lots of issues!

**Comment by spymastermatt** [comment]
@Girtablulu Did you try checking for other profile folders? I'll close this issue in a couple of days if I haven't heard from you.
