### ISSUE TITLE
Change Font Color on Menu Bar

### ISSUE THREAD

**Issue by AdmiralAsshat** [spymastermatt/thunderbird-monterail#17]
The Monterail theme looks great when the Menu Bar is hidden, but when it's left on, the text is very difficult to read:

![thunderbird monterail menu bar](https://cloud.githubusercontent.com/assets/5513487/25552322/5be3e1ec-2c64-11e7-974e-02138049fd9a.png)

Can we change the font color on Menu Bar text to be something more legible?

I'm looking at using something from  [this site](https://material.io/color/#!/?view.left=0&view.right=0&primary.color=00838F) as reference to look at potential colors that work well on that teal background.

**Comment by spymastermatt** [comment]
Hey all, sorry for being quiet for the past few days, I have been working on a big update (coming tomorrow hopefully) which fixes almost all open issues (including this one)

**Comment by spymastermatt** [comment]
@AdmiralAsshat 
This should now have been resolved by a complete rewrite (and refactor).
Please discard the old versions and download the new ones.

Thanks everyone for helping out with bug reports and fixes!!
