### ISSUE TITLE
Ugly window background on Windows 7

### ISSUE THREAD

**Issue by lumiru** [spymastermatt/thunderbird-monterail#18]
Hi,

I use your theme on Windows 7. I got an ugly blue titlebar over the transparent Windows 7 theme.

![ugly-blue-titlebar](https://cloud.githubusercontent.com/assets/4085705/25554469/67d9e072-2cce-11e7-90d8-d25e2c9f55b3.png)

I fix it by removing white background on "window" tag and blue background on "#navigation-toolbox".

**Comment by spymastermatt** [comment]
Hey all, sorry for being quiet for the past few days, I have been working on a big update (coming tomorrow hopefully) which fixes almost all open issues (including this one)
