### ISSUE TITLE
Calendars check box all white (Lightning)

### ISSUE THREAD

**Issue by pled** [spymastermatt/thunderbird-monterail#19]
When using Lightning as calendar, on the left pane listing the calendars, the check boxes are always blank no matter if the box is checked or not.

**Comment by Coeur-Noir** [comment]
Hi,

I can confirm this problem with blank check boxes in lightning
on Ubuntu 16.04 / Unity / TB 45.8.0

**Comment by j0r0** [comment]
Could this be the same as #7 
Sounds like it, and i reproduced it as well

**Comment by spymastermatt** [comment]
Hey all, sorry for being quiet for the past few days, I have been working on a big update (coming tomorrow hopefully) which fixes almost all open issues (including this one)

**Comment by spymastermatt** [comment]
Hi everyone.
This should now have been resolved by a complete rewrite (and refactor).
Please discard the old versions and download the new ones.

Thanks everyone for helping out with bug reports and fixes!!
