### ISSUE TITLE
Mail subject on 4/3 screen too big

### ISSUE THREAD

**Issue by Aguay-val** [spymastermatt/thunderbird-monterail#2]
Hi !

First of all thanks for this amazing work !

I just have an issue with the size of the subject. 

![selection_073](https://cloud.githubusercontent.com/assets/2204373/25472834/47104324-2b2d-11e7-9478-020dbd134c58.png)

I think it would be awesome if text size would be more responsive depending of the size available.

Here, it seems to be fixed size.

**Comment by spymastermatt** [comment]
Hi glad you like it.
Oh ok that's odd. I'm not sure how feasible responsive text size is (having tried to find a way several times when doing web development and never found anything)
However, at the very least the subject box should expand to accommodate the text or elide the subject (probably the former)

**Comment by j0r0** [comment]
Hi,
I just changed display:flex to block and it seems that it solves the problem 

![image](https://cloud.githubusercontent.com/assets/370737/25477750/e640438e-2b3e-11e7-8d8e-00bbcb20bd5c.png)

The CSS now looks like this 
```
#expandedHeader2Rows #expandedsubjectRow, #expandedHeader2Rows #expandedtoRow {
	display: block !important;

}
```

**Comment by Aguay-val** [comment]
Thanks !

This seems to fix this issue!

Thanks againt :+1:

**Comment by spymastermatt** [comment]
thanks @j0r0, I have merged your pull request. Marking this as fixed.

**Comment by AntoineTurmel** [comment]
Good that I checked closed issues before ;) Thanks for the fix !
