### ISSUE TITLE
Twisty icons (to expand/collapse folders) hardly visible

### ISSUE THREAD

**Issue by pinkdroyd** [spymastermatt/thunderbird-monterail#20]
I recently started using the monterail theme. My only problem with it is that because of the dark background I can now hardly see the black icons to expand and collapse folders in the folder tree:

![monterail1](https://cloud.githubusercontent.com/assets/4980307/25583929/32677b12-2e94-11e7-8cde-bb0a4d5ddaef.png) ![monterail2](https://cloud.githubusercontent.com/assets/4980307/25583940/377fc410-2e94-11e7-9476-3db597ae8908.png)

I tried adjusting the color with 
`treechildren::-moz-tree-twisty {
	border: white;
}`
but that does not work. I can only change `background-color`, which leads to a quite ugly result.

Can you help me fix this?

Thanks for a really nice theme!

**Comment by conema** [comment]
Hi @pinkdroyd, you are right. I think that we need to change the svg icon with a whiter one by creating a css rule that overwrite the current list-style-image (found in tree.css - row 316). 
I will try to do it in the next days. I will update you.

**Comment by spymastermatt** [comment]
Hey all, sorry for being quiet for the past few days, I have been working on a big update (coming tomorrow hopefully) which fixes almost all open issues.

Thanks @conema for helping out but to save you time I have already done this :)
Are you interested in helping to contribute more, I'd love some assistance as the theme rather took off more than I was expecting?

**Comment by conema** [comment]
@spymastermatt Absolutely! I'd be very happy to help you.

**Comment by spymastermatt** [comment]
Hi everyone.
This should now have been resolved by a complete rewrite (and refactor).
Please discard the old versions and download the new ones.

Thanks everyone for helping out with bug reports and fixes!!
