### ISSUE TITLE
Install on Windows

### ISSUE THREAD

**Issue by jrock2004** [spymastermatt/thunderbird-monterail#21]
So I just installed newest Thunderbird and downloaded the zip file. I took the chrome folder and placed in it `C:\Users\john.costanzo\AppData\Local\Thunderbird\Profiles\dxb5zkup.default`. I opened thunderbird and I see no changes. Here is what the content of the folder looks like

![image](https://cloud.githubusercontent.com/assets/655716/25593002/02d8e3aa-2e89-11e7-987f-95643074393d.png)

What I am doing wrong

**Comment by fwhcat** [comment]
It's written explicitely on the readme

> Simply copy the css file for whichever theme you want to use and rename it userChrome.css and then restart Thunderbird
But before that, I'd do a backup of the original userChrome.css if I were you.

**Comment by spymastermatt** [comment]
@fwhcat From the look of @jrock2004's screenshot, he has done. his userChrome.css has the exact same file-size and modification time as the theme css files.

@jrock2004 That all looks good to me. Try doing a search on your computer for a file called abook.mab (there should be one in your thunderbird profile folder). That might show up if thunderbird is using a different profile folder.
If nothing shows up, you can also check it by opening Thunderbird's preferences, going to the advanced tab and clicking the 'Config Editor' button. Accept the warning and then search for *directory*. Look for 'mail.server.server1.directory' which should show you the path to your profile folder (ignore the parts after kjghkdskgdgdjhgd.default).
If you have multiple mail.server.server2, 3 etc. check that they all point to the same profile directory. If they don't, try copying your chrome folder to the other directory(ies) and restart Thunderbird each time. That way you can see which one is being used.

Let me know if that works or not.

**Comment by Masclaux** [comment]
Hi You are in the wrong path. UserChrome need to be in 

C:\Users\username\AppData\**Roaming**\Thunderbird\Profiles\xxxxxxx.default

**Comment by spymastermatt** [comment]
@Masclaux good spot!
@jrock2004 can you try the directory @Masclaux suggested and let us know if it worked so I can close the issue.
The correct directory specification for Windows is now in the readme thanks to the amazing @conema!!

**Comment by Conker1r** [comment]
@jrock2004 
I found that I needed to apply new permissions to the chrome folder before or after you copy it over to your profile directory. I removed the 'read-only' permission and applied it. 
This worked for me on Windows 10

![capture](https://cloud.githubusercontent.com/assets/20133975/25728917/39c1f79a-30ef-11e7-9cee-7f5053352f18.PNG)

**Comment by jrock2004** [comment]
@Masclaux answer was the right one. Sorry took so long to respond

**Comment by spymastermatt** [comment]
@jrock2004 No worries, took me ages to respond for a while... we're all busy :)
@Masclaux Thanks for supplying the answer

@Conker1r Thanks for the tip! If we find a lot of people have the same problem I'll add your tip to the readme

**Comment by Masclaux** [comment]
@spymastermatt no problem thank you for you work ;)
