### ISSUE TITLE
Sort list not visible

### ISSUE THREAD

**Issue by walkero-gr** [spymastermatt/thunderbird-monterail#29]
Great update and very nice work you done here. There is still a problem with the sorted column in the Subjects list of the emails. It is not visible which column as only the Default column has the arrow visible, and even if you click to change the order, the arrow doesn't change. Also it doesn't change if you click to sort with an other column.

I use Thunderbird 45.8.0 under Linux Mint

**Comment by conema** [comment]
Hi @walkero-gr, I can't reproduce the problem that you are describing. Are you speaking about this little triangle that is used for change the order of the column?
![immagine](https://cloud.githubusercontent.com/assets/12801153/25760549/95521994-31d7-11e7-8275-a61add1ced79.png)

If yes:
- What theme are you using (dark, fulldark, etc..)?
- The button works without the theme?
- Even if you click the button, the order remain the same?

Let me know.

**Comment by walkero-gr** [comment]
Sorry for the late answer.

Yes, I am talking about the triangle at the columns header, in the emails list. My setup has the Subject, From, Date, Size columns.

1. I am using the dark theme, but this happens at all the themes
2. Yes. The arrow shows the sorting column and the order.
3. If I click the button, the order changes, but the arrow doesn't. If I click at an other column, the order also changes as it should, but the arrow remains at the previous column.

**Comment by spymastermatt** [comment]
This should now be fixed :)
