### ISSUE TITLE
full dark theme same as dark

### ISSUE THREAD

**Issue by ddo** [spymastermatt/thunderbird-monterail#3]
My thunderbird v45.8.0

**Comment by hogar1977** [comment]
Same for me, but with an additional twist... Light and dark themes look the same (dark left side pane, dark top, light (glaringly white) toolbar and email list and email itself **and** the selected folder in the left side pane is not highlighted, i.e. there is no way to see which folder is selected.

I am using Antergos (basically Arch) with Gnome 3 and Adapta-Nokto-Eta theme. If I pick Adwaita theme, things get even worse in a sense that there is no dark theme-ing going on at all...

I would prefer to use full dark theme if possible. Any pointers on what to change in the css file to try and test this more?

**Comment by spymastermatt** [comment]
So to clarify a little, the dark and fulldark themes are not themes as such, but are for use **with** dark and fulldark themes. If you use a light theme, dark will look the same as light.

As to why it isn't working with Adapta-Nokta I will investigate tonight

**Comment by Tromzy** [comment]
Dark css don't seem to work with KDE Plasma dark theme either.

**Comment by spymastermatt** [comment]
@hogar1977, @Tromzy could you post screenshots so I can see what's wrong?
I have tried the Adapta-Nokto-Eta theme with fulldark, Adwaita with light and Breeze light and dark with corresponding userChrome and they seem fine on my machine.
I am currently working on a userChrome-gtk.css which should automatically adapt to the current gtk theme, after which I will make dark and fulldark be actual themes with specified colors.

**Comment by Tromzy** [comment]
![thunderbird_black](https://cloud.githubusercontent.com/assets/1344491/25519805/9bbd5fa2-2bf9-11e7-828a-a8cd12b4656f.png)

**Comment by Tromzy** [comment]
That's the Dark theme.

**Comment by ddo** [comment]
full dark theme
![screenshot from 2017-04-28 15-39-19](https://cloud.githubusercontent.com/assets/1265628/25521421/a88ff99e-2c29-11e7-9c6e-3e66afe8b69b.png)

**Comment by spymastermatt** [comment]
Hey all, sorry for being quiet for the past few days, I have been working on a big update (coming tomorrow hopefully) which fixes almost all open issues (including this one)

**Comment by conema** [comment]
@ddo @hogar1977 @Tromzy Hi guys, I made two PR that solve your problems.
#23  Fix for full-dark theme
#22 Fix for dark theme
Go check them =)

**Comment by spymastermatt** [comment]
Hi everyone.
This should now have been resolved by a complete rewrite (and refactor).
Please discard the old versions and download the new ones.

Thanks everyone for helping out with bug reports and fixes!!

**Comment by ddo** [comment]
confirmed all themes works. ty

**Comment by spymastermatt** [comment]
@ddo Perfect , thank you!

**Comment by Tromzy** [comment]
I can confirm it too ! Thanks !
