### ISSUE TITLE
Is there any way to disable square tabs.

### ISSUE THREAD

**Issue by Abhinav1217** [spymastermatt/thunderbird-monterail#30]
From `userChrome.css`
```
/* Uncomment to use square tabs (square tabs are enabled anyway for all except system.css) */
/* @import "tweaks/square-tabs.css"; */

```
I want to use light theme ( or sometimes dark theme ) but I am not really a fan of square tabs. But this looks like I can't disable it without using system.css .  Is there any way I can have nice firefox australis 'esk curved tabs for those who want it?

P.S. I am working on css file for this but I am not really a designer.  Plus I do not want to loose work when you provide an update.

**Comment by conema** [comment]
@Abhinav1217 Yes, it is possible to disable square tabs!
You need to open the theme that you want to edit (for example dark.css, located in the themes folder) with a text editor and comment these rows:

- **Line 9**

`@import "../tweaks/square-tabs.css";`
To:
`/*@import "../tweaks/square-tabs.css";*/`

- **Line 77**

`background: var(--dark-light-background) !important;`
To:
`/*background: var(--dark-light-background) !important;*/`

I hope this could help you!

**Comment by pinkdroyd** [comment]
@conema tried this with monterail, the problem here is that by completely excluding square-tabs.css the font color is dark on a dark background. This fixes this issue:

Do as you said in the _theme_.css in line 77:

`background: var(--dark-light-background) !important;`
To:
`/*background: var(--dark-light-background) !important;*/`

Go to square-tabs.css, and exclude everything except for this:
```
.tabmail-tab .tab-text {
	color: var(--menu-text-color) !important;
}
```

As I mentioned before, this was **only tested for the monterail theme**, not dark, light, or fulldark

**Comment by conema** [comment]
@pinkdroyd Thank you for the correction! I didn't think about it. However my workaround should work with the dark, full-dark and light theme.

@Abhinav1217 Let us know!

**Comment by Abhinav1217** [comment]
@conema 
Your method does bring back the curved tab but just like @pinkdroyd said, There was an issue of dark text on dark background ( and light text on light background for light.css ) for unselected tabs i.e. tabs other than current tab. So his method is what I would recommend.

After working on thunderbird with light.css all day, I would suggest a bit of a contrast adjustments at some places. Also in my case, I think you have used a custom scrollbar, which is much thicker that my system one, does not show on email part.

Thick custom scrollbar on message list
![screenshot from 2017-05-05 19-11-26](https://cloud.githubusercontent.com/assets/740584/25747977/f2321bda-3198-11e7-8689-7de8196eb0b8.png)
and on account list
![screenshot from 2017-05-05 19-11-51](https://cloud.githubusercontent.com/assets/740584/25747975/f22d5370-3198-11e7-9952-e4f09c1cdf8d.png)
but not on Email section.
![screenshot from 2017-05-05 19-13-01](https://cloud.githubusercontent.com/assets/740584/25747976/f22dcec2-3198-11e7-9f1a-535a4ff87ab5.png)

icon before inbox and account name blends into the background.
![screenshot from 2017-05-05 19-12-14](https://cloud.githubusercontent.com/assets/740584/25747974/f22cfc40-3198-11e7-9d17-8eb96cd4fe36.png)


Now I should stop finding issues and thank you for making such beautiful themes. It was a nice treat for eyes.

**Comment by conema** [comment]
@Abhinav1217 I'm happy to hear that!
Thanks for the suggestions and for reporting the issue with the scrollbar, I will look for it. Issues are always welcomed, don't be afraid!

By the way you should thank @spymastermatt, he's the creator!
