### ISSUE TITLE
Can't increase font size (Mac OSX)

### ISSUE THREAD

**Issue by powelleric** [spymastermatt/thunderbird-monterail#36]
Not sure if this theme is even supported on Mac but I was able to get most everything working.  The only problem is that the font seems small and I have adjusted the line below in `userChrome.css` but it does not change anything.

` --subject-line-font-size: 200%;`

What is everyone else's experience with Mac?  I wonder if a previous extension messed up the font mappings...

**Comment by conema** [comment]
Hi @powelleric, this theme should work without problems with Mac OSX.

May you send a screenshot of your page, so I can see if it is *normal*?
What text do you want enlarge? (The code that you had pasted should edit only the email subject in the header of email)
It is possibly enlarge all the text present in the theme and I will give you istructions to do it after you answer these question.

Just a personal information, how did you installed the theme, the steps are the same as the linux version?

Let me know, thanks.

**Comment by powelleric** [comment]
@conema 

Thank you for your quick response.  You are correct.  The parameter that I was changing was just for the email subject and that was working just fine (now that I know what it is actually doing).

Attached is a screenshot. I have included the Mac toolbar at the top of the screen to give you some perspective.  You can see the text is a bit smaller than comfortable.  Text size more like that in the body of the email would be better.  

Oh, and a small other issue is that the toggle arrows on the left of the inbox accounts is running into the account name.  I can create a new issue for that if you wish.

![screen shot 2017-05-05 at 1 59 19 pm](https://cloud.githubusercontent.com/assets/11025490/25762318/91842abe-319b-11e7-8203-060be769fba8.png)

**Comment by conema** [comment]
@powelleric You're welcome!
I agree with you, it's a bit small.

However, there are a lot of way to increase the font size, the important thing is to add all the code to the end of *userChrome.css* file.
For example, this code should enlarge folder, thread (where email are) and menu :
`#mailContent{
  font-size: 15pt !important;
}`

Obviously you can change the dimension of the font by changing the value *15*.

Other ways are: 
- #threadTree treechildren: for edit only the thread list
- *#mail-toolbox*: for edit only the upper menu
- *#folderTree*: for edit only the folder menu


I think that we will add this codes in the future, thanks for opening this issue!

Best regards, let me know if you need more help. I will answer as faster as I can (now it's a bit late :P).

**Comment by powelleric** [comment]
That worked great.  15pt was much, much too big.  I scaled it back to 12 and it looks perfect, so I'd say that the default was probably 10pt or smaller - probably too small for most people's taste.

Oh, and for anyone else, do just as @conema said: 
Add the new properties at the very end of the file, after the closing brace for `:root`. And leave the comment character at the beginning of `mailContent`.  It is CSS so actually is referring to an id, not making a comment.
