### ISSUE TITLE
Arrow to toggle expansion of account folders is too close to envelope icon (Mac OSX)

### ISSUE THREAD

**Issue by powelleric** [spymastermatt/thunderbird-monterail#38]
As the issue says, the arrow runs into the envelope icon in the folder pane.  Doesn't look like this on the screenshots, so I'm guessing this is a small bug with Mac.

![2017-05-05_14-42-31](https://cloud.githubusercontent.com/assets/11025490/25763599/2046d300-31a1-11e7-8c8c-7e919719a69f.jpg)

**Comment by conema** [comment]
@powelleric #39 is ready. Sorry  for the wait, I was having problem with my local repository 😄 
Let me know if it works!
