### ISSUE TITLE
It doesn't work properly for me...  not modded fully

### ISSUE THREAD

**Issue by FreshhhHub** [spymastermatt/thunderbird-monterail#43]
It doesn't work properly for me...  

I followed all those steps : 

- renaming extracted folder as "chrome"

- edited system.css to import the theme wanted

- copied it manually to C:\Users\MyUserName\AppData\Roaming\Thunderbird\Profiles\RANDOMDIR.default\chrome

but something isn't working properly: 
only top bar color is modded not the left panel and main background...

tried to import two different themes and same thing... 

what could be wrong?

**Comment by qwertychouskie** [comment]
> edited system.css to import the theme wanted

You are supposed to edit userChrome.css, in the chrome folder.

**Comment by FreshhhHub** [comment]
yeah you are right i guess i need some sleep (:
