### ISSUE TITLE
* TIP * Ultimate CSS Gradient Generator

### ISSUE THREAD

**Issue by FreshhhHub** [spymastermatt/thunderbird-monterail#46]
not an issue but a suggestion...  
this online tool might be useful for themers... 

Ultimate CSS Gradient Generator
A powerful Photoshop-like CSS gradient editor from ColorZilla. 

http://www.colorzilla.com/gradient-editor/

**Comment by spymastermatt** [comment]
Thanks for this tip @FreshhhHub  :)
I am hoping to work on a new project, starting in a few days, which is a web page that allows people to create their own custom userChrome from a base theme (basically the ones on here) and then using sliders, toggles etc to customise (hopefully with a live preview) So i'll probably find out if the colorzilla guys can let me embed their gradient creator for that purpose.

**Comment by spymastermatt** [comment]
I am, however, going to close this issue so it's not on the list :)
