### ISSUE TITLE
Folder pane background just plain grey

### ISSUE THREAD

**Issue by SimonAltrogge** [spymastermatt/thunderbird-monterail#50]
As you can see in the picture, the background of the folder pane has not changed for me. I am using the monterail theme for Thunderbird 52 on Windows 10.
![folder-pane](https://cloud.githubusercontent.com/assets/8720147/26241407/cf45832c-3c84-11e7-82e8-516947e88754.PNG)

**Comment by spymastermatt** [comment]
Hi @SimonAltrogge thanks for pointing this out. You are correct. In fact on windows 7 the theme appears utterly broken :( with the tab bar and toolbox also totally unaffected by the userChrome.css

I will have a look at why this is. Unfortunately as I use linux, windows bugs are a bit more difficult for me to track down and fix. How willing are you to try out a few changes if I create a branch for you to update from?

**Comment by SimonAltrogge** [comment]
Hi @spymastermatt,
thank you for your attention to this matter. I am definitely willing to try out changes, if you do not mind having to wait for a response a day or two, since I cannot guarantee always being able to test something right away.
I really appreciate your dedication to fix bugs for Windows, even though you do not use it yourself!

**Comment by spymastermatt** [comment]
That's great! OK I will have a look through the code and see if I can see an obvious problem. I also need to update my thunderbird and check it's not a problem with the version rather than the OS.
Thanks for helping out!!

**Comment by matiasblomqvist** [comment]
I am having the same problem with Xubuntu 16.04

**Comment by spymastermatt** [comment]
Problem was the combination of dark folders tweak with non-system theme. Now fixed :)

**Comment by SimonAltrogge** [comment]
Yes, it is. Thank you very much. The text is still black though and therefore not very readable. Is this also a bug or do I have to change any settings?

**Comment by spymastermatt** [comment]
Quite right. Thanks for spotting that. It didn't show up for me because I have a theme with white text by default. It is fixed now

**Comment by SimonAltrogge** [comment]
Perfect, thank you very much!
