### ISSUE TITLE
Enabling or disabling tweaks/dark-folder-pane.css does not change background color

### ISSUE THREAD

**Issue by qwertychouskie** [spymastermatt/thunderbird-monterail#53]
Thunderbird 45.8.0, Greybird, Xubuntu 17.10

**Comment by spymastermatt** [comment]
The dark folders tweak is for "dark folder pane style when using the **system theme with dark menus**" (i.e. Ambiance)
If you are using a system theme with light menus (like Greybird) then it will have almost no effect
