### ISSUE TITLE
Square tabs

### ISSUE THREAD

**Issue by geek1011** [spymastermatt/thunderbird-monterail#6]
I (personally) think this theme would look more consistent if the tabs were square. 

Also :+1: on this great theme. It's the first nice one I have seen in a while.

**Comment by j0r0** [comment]
Not sure i understand...as i see tabs are "square?"

![image](https://cloud.githubusercontent.com/assets/370737/25484669/42ac72fc-2b5b-11e7-8fbe-daa1ea1ad29b.png)

**Comment by spymastermatt** [comment]
Interesting.
I will probably create a square tabs version when I have fixed some of the other issues.
I am looking at restructuring the css to bring customisation into a single file so I'll probably add the square tabs feature in there as a toggle.

**Comment by geek1011** [comment]
No, they should be square. Right now, they do not appear to be square, they are still round.

**Comment by spymastermatt** [comment]
Hey all, sorry for being quiet for the past few days, I have been working on a big update (coming tomorrow hopefully) which fixes almost all open issues. Once i have pushed that and fixed a couple of other minor bugs, I will look into this.

**Comment by spymastermatt** [comment]
Hi everyone.
Square tabs are now default for the light, dark, fulldark and monterail variants, and optional for the system variant.
Please discard the old versions and download the new ones.

Thanks everyone for helping out with bug reports and fixes!!
