### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by allienworks** [spymastermatt/thunderbird-monterail#61]
Hey @spymastermatt,
first of all, amazing work on this theme! It truly brings Thunderbird to the next level.

I wanted to ask – how is this licenced? You haven't mentioned it anywhere in the repo/readme.
Thanks!

**Comment by spymastermatt** [comment]
Hi @allienworks Glad you like the theme!

Re the license I never really thought about it but I guess probably GPLv3. I'll have a look tonight at the different licenses and pick one (basically whichever gives people the most freedom). Once I have, I'll update the readme and the code

**Comment by spymastermatt** [comment]
I have chosen the GPLv3 to give the most freedom :)
