### ISSUE TITLE
Main menu became unreadable

### ISSUE THREAD

**Issue by walkero-gr** [spymastermatt/thunderbird-monterail#63]
After the commit #876559fd908868842a9f3df9ec852c1f21d0bad9 the change at the file dark.css made the main menu (from the burger button) of Thunderbird to have white text, and unreadable, because it has light grey background. When I reverted the change, the color became again black.

Thunderbird v.52.1.1 on Linux mint

**Comment by PrzemekSkw** [comment]
Hi, I have set monterail theme and have the same problem. I don't know what to change to make menu readable.
