### ISSUE TITLE
Very big menu separators in every theme except the system theme

### ISSUE THREAD

**Issue by jdreesen** [spymastermatt/thunderbird-monterail#65]
When e.g. writing a new mail the menu separators of the top flyout menu items are very big.
This appears in every theme except the system theme.

This is how it looks (in monterail theme):
![menu-separator](https://user-images.githubusercontent.com/424602/27706957-e8fbe7c0-5d13-11e7-8d8c-e059e69b6153.png)

I'm using latest thunderbird on Windows 10.

**Comment by spymastermatt** [comment]
@jdreesen Could you try the very latest menu colors fix  I have just pushed?

**Comment by jdreesen** [comment]
Now they aren't dark anymore, but still rather big:
![menu-separator](https://user-images.githubusercontent.com/424602/27709573-e9031a0a-5d1c-11e7-88e1-63a6434ecfed.png)

Here's the system theme for comparison:
![menu-separator-system](https://user-images.githubusercontent.com/424602/27709575-ea470bba-5d1c-11e7-9837-4e0b9e3efee8.png)

**Comment by FreshhhHub** [comment]
i like the separator bigger maybe not as big than first screenshot but sorry i think your much thinner version is uglier (personal taste)...  please share a medium size separator solution instead :)

**Comment by spymastermatt** [comment]
@jdreesen Hmm, I''ll look into this.
@FreshhhHub Personal taste aside, my code shouldn't have any impact on the size of separators. The only reason I change them at all is because the colors are not suitable on some themes (e.g. when I use the monterail theme with a full dark gtk theme, which has light separators)

**Comment by conema** [comment]
@jdreesen Here a quick workaround for you, add this code at the end of  _base.css:

```css
menuseparator{
    padding-top: 0 !important;
    padding-bottom: 0 !important;
}
```
