### ISSUE TITLE
Light coloured text on menu bar in full dark theme

### ISSUE THREAD

**Issue by appolyon** [spymastermatt/thunderbird-monterail#66]
The text is legible on all the other themes except in the full dark theme where it is too light to read.

![Full dark menu](https://i.imgur.com/BFzZeoT.png)

**Comment by conema** [comment]
Hi @appolyon, you can edit the font color by editing the "dark-text-color" variable (themes/fulldark.css, row 36). I personally prefer this color, but if you like, you can edit it and even recommend a better color.

**Comment by appolyon** [comment]
Thanks for the tip @conema - I think it would look better to change the menu bar background colour to match the mail toolbar and leave the font colour as is. Do you know where I would need to make that edit?

**Comment by conema** [comment]
Sorry @appolyon! I misunderstood what you wrote, it was solved with my recent PR (#68), so you need only to update your theme.

**Comment by appolyon** [comment]
@conema thank you very much for the update!
