### ISSUE TITLE
Tickbox does not show checkmarks

### ISSUE THREAD

**Issue by cwitt2013** [spymastermatt/thunderbird-monterail#7]
Hi,

when I check a 'tick box' I do not see a check mark. 

I use Fedora 25, Thunderbird 52 and the monterail theme.

Thank you for the great theme. I really appreciate the work!!!

**Comment by spymastermatt** [comment]
@cwitt2013 Glad you like it!
I must be being dumb because I can't find any checkboxes.Could you point me to where they were so I can fix them.
Thanks for taking the time to report this

**Comment by syphernl** [comment]
Same problem here (Ubuntu 16.04 / XFCE). There are checkboxes in the calendar component to select which calendars are visible. Same for the todo list

![image](https://cloud.githubusercontent.com/assets/639906/25517760/1763283e-2bf1-11e7-964c-574531b56ca0.png)

As you can see, there is a difference between checked and unchecked but its very hard to distinguish between the two.

**Comment by spymastermatt** [comment]
Hmm ok. It's odd as I didn't change any check box code AFAIK.
Thanks for finding that for me. I'll look into it.

**Comment by cwitt2013** [comment]
thy @syphernl 
This is the problem I meant

**Comment by spymastermatt** [comment]
Hey all, sorry for being quiet for the past few days, I have been working on a big update (coming tomorrow hopefully) which fixes almost all open issues (including this one)

**Comment by spymastermatt** [comment]
Hi everyone.
This should now have been resolved by a complete rewrite (and refactor).
Please discard the old versions and download the new ones.

Thanks everyone for helping out with bug reports and fixes!!
