### ISSUE TITLE
Plasma appearasnce 

### ISSUE THREAD

**Issue by NikEfth** [spymastermatt/thunderbird-monterail#8]
Thank you for this much needed theme. 
In plasma the themes are not working properly. Wrong colours of backgrounds and fonts.

**Comment by spymastermatt** [comment]
Hi @NikEfth glad you like the theme.
I am using plasma and the panels seem the right colours for me.
Can I check which userChrome and plasma theme you are using?
Also, check that you have the correct GTK theme set in plasma settings:  Application Style > GNOME Application Style (GTK)

Thanks

**Comment by NikEfth** [comment]
Hi! 

I tried them all. Only the montreal was ... almost correct. The dark and very dark were with the same color as my plasma theme. Also the color of the fonts on the top tabs is wrong. I am using the latest version of all Plasma  from the Arch repo.

**Comment by spymastermatt** [comment]
@NikEfth, the dark and full dark themes currently do use the gtk theme colours, see issue #3 for an explanation. However, that will be changing in the next couple of days and then light, dark and fulldark will become actual fixed colour themes (with easily configurable colours) :)

**Comment by NikEfth** [comment]
Cheers

**Comment by spymastermatt** [comment]
Hi everyone.
This should now have been resolved by a complete rewrite (and refactor).
Please discard the old versions and download the new ones.

Thanks everyone for helping out with bug reports and fixes!!
