### ISSUE TITLE
AppData and Tools not found

### ISSUE THREAD

**Issue by Wulfheart** [spymastermatt/thunderbird-monterail#82]
Hello,

in the current windows version isn't AppData no longer available. I also don't know how to find the "Tools". Any suggestions?

**Comment by conema** [comment]
Hi @Wulfheart, AppData folder is available with Windows 10, to access it, write _%appdata%_ into the address field in any folder and after that press enter.
![immagine](https://user-images.githubusercontent.com/12801153/35883983-753b6aa2-0b89-11e8-88f2-4ec9db09752e.png)
