### ISSUE TITLE
No background colors

### ISSUE THREAD

**Issue by nd-** [spymastermatt/thunderbird-monterail#9]
Hello,
thanx for your work.
I tried the themes but i have no background colors in Thunderbird, all is white.
I tested the 4 themes with my profile, but I have some extensions, so I tested with a clean new profile: nothing, nada, nichts, rien...
I can see the font and the icons, but the background is all white.

Thunderbird 52.0.1 (64 bits) on OSX 10.11.6

**Comment by spymastermatt** [comment]
Hi @nd- glad you like it. Does the light variant work for you?
I think I may have been super confusing with my naming as this seems to be something that crops up a lot.

The light, dark and fulldark variants are for use with gtk themes that are light/dark/fulldark. They are not dark etc variants in themselves.

I will fix this in a few days, with one userChrome-gtk which should automatically adapt to the current theme, after which I will make the dark and fulldark variants true 'themes' with specified dark colours.

If that's not the issue could you post a screenshot of the dark variant so I can see the issues.
Thanks for reporting the bug :)

**Comment by fxbenard** [comment]
![2017-04-28_09-21-44](https://cloud.githubusercontent.com/assets/802114/25518622/cb6840d2-2bf4-11e7-9f1e-393e0b12d883.png)
Dark style applied on my windows 10 install

**Comment by nd-** [comment]
Same problem as @fxbenard on OSX: no background colors, and white text on white background in the folder panel.

**Comment by spymastermatt** [comment]
Hi @nd- @fxbenard, as I say, if you are using windows/macos only the light theme wil work with your system theme. The monterail theme should also work as it does specify it's own colours.
The dark and full-dark themes don't actually specify dark colours, but pull them from the current system theme, designed for use with dark/fulldark system themes. 

I am working on changing this so that the dark/fulldark themes specify their own colours and are configurable and will let everyone know when that work is finished

**Comment by conema** [comment]
Hi @nd- @fxbenard, watch out my new pull request, the dark theme should be working now.
[Pull request](https://github.com/spymastermatt/thunderbird-monterail/pull/22/files)

**Comment by spymastermatt** [comment]
@conema Thank you for this! I will add it to the dark theme after I push the userChrome-gtk.css (hopefully tomorrow), which will allow people with dark themes to use their gtk colors (as the current dark theme does).

Everybody:
Sorry for being quiet for the past few days, I have been working on a big update (coming tomorrow hopefully) which fixes almost all open issues (including this one)

**Comment by spymastermatt** [comment]
Hi everyone.
This should now have been resolved by a complete rewrite (and refactor).
Please discard the old versions and download the new ones.

Thanks everyone for helping out with bug reports and fixes!!

**Comment by fxbenard** [comment]
@spymastermatt It works like a charm. Thanks for those awesome improvements

Can you tell me the way to change the light blue of monterail by the orange of the dark theme with your new system in the selected message column. Sure it will rock ;)

**Comment by conema** [comment]
@fxbenard Are you speaking about the thread collumn, where email are displayed? 

I will help you tomorrow with that (GMT+2), unless @spymastermatt doesn't anticipate me 😀

**Comment by fxbenard** [comment]
@conema Yes exactly, the thread column.

**Comment by spymastermatt** [comment]
@fxbenard If you edit your userChrome.css by uncommenting the line: *--message-list-highlight-background-color*, you can change the highlight color for the message list. FYI the orange from the dark/light themes is: #3DAEE9

**Comment by fxbenard** [comment]
@spymastermatt Lovely it works as expected, thanks for the tip, your new system is really useful for little twists like that.
FYI: your orange is: #F07746
Thanks
